Feat : avatar and badges done
anuj-kumary/Eagle pull request #1
Opened 2022-01-27 13:28 UTC by anuj-kumary

2022-01-27 15:38 UTC, lomesshh approved these changes
Looks good !

2022-01-27 16:52 UTC, Hnh013 commented
looks good to merge , great work !

2022-01-27 16:53 UTC, Hnh013 approved these changes
approving changes now!

2022-01-27 20:22 UTC, Rohanmond commented
Look good, great!

2022-01-28 08:39 UTC, Rohanmond approved these changes

2022-01-29 16:57 UTC, Parul1999 commented on components/Badge/badge.css
> +    border: 2px solid #fff;
Don't hard-code colours.

2022-01-29 16:58 UTC, Parul1999 commented on components/Badge/badge.css
> +    bottom: 4%;
Use same units.

2022-01-29 17:00 UTC, Parul1999 commented on components/Badge/badge.html
> +        alt=""" />
alt = ""

2022-01-29 17:05 UTC, Parul1999 requested changes
1)Use same units iin CSS
2) don't hard-code colurcode.
3) Use semantic tags

2022-01-29 17:06 UTC, Parul1999 commented on components/Badge/badge.html
> +    <div class="content-heading">Profile Avatar</div>
Use Semantic Tags

2022-01-30 14:25 UTC, Parul1999 approved these changes

2022-01-31 17:38 UTC, merged